In [39]:
import pandas as pd
import numpy as np
import math
from numpy.linalg import norm

In [60]:
league = pd.read_csv('League of Legends pro play Champ Stats from Gol.gg - 12.12.csv')

In [61]:
league.sort_values(by='Wins', ascending=False)

,Champion,Picks,Bans,Presence,Wins,Losses,Winrate,KDA,Avg BT,GT,CSM,DPM,GPM,CSD@15,GD@15,XPD@15
2,Gnar,443,229,74%,227.0,216.0,51%,2.9,6.1,31:34:00,8.3,534.0,402.0,6.9,228.0,136.0
0,Wukong,373,347,79%,212.0,161.0,57%,3.5,4.9,32:05:00,5.3,329.0,337.0,-7.0,-135.0,-219.0
18,Aphelios,293,69,40%,159.0,134.0,54%,3.6,5.2,31:49:00,9.2,571.0,433.0,2.5,49.0,24.0
6,Renata Glasc,265,325,65%,151.0,114.0,57%,4.2,5.3,31:37:00,0.8,172.0,244.0,-6.3,50.0,20.0
11,Viego,294,126,46%,149.0,145.0,51%,3.5,6.5,31:28:00,5.7,297.0,345.0,5.2,135.0,160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,Quinn,0,0,0%,NaN,NaN,NaN,NaN,-,0:00,NaN,NaN,NaN,NaN,NaN,NaN
157,Warwick,0,0,0%,NaN,NaN,NaN,NaN,-,0:00,NaN,NaN,NaN,NaN,NaN,NaN
158,Zyra,0,0,0%,NaN,NaN,NaN,NaN,-,0:00,NaN,NaN,NaN,NaN,NaN,NaN
159,Illaoi,0,0,0%,NaN,NaN,NaN,NaN,-,0:00,NaN,NaN,NaN,NaN,NaN,NaN
160,Nilah,0,0,0%,NaN,NaN,NaN,NaN,-,0:00,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
lol = league.drop(['Champion','Presence','Winrate','KDA','Avg BT','GT','CSD@15','GD@15','XPD@15'],axis = 1)

In [63]:
lol

     Picks  Bans   Wins  Losses  CSM    DPM    GPM
0      373   347  212.0   161.0  5.3  329.0  337.0
1      250   453  130.0   120.0  9.3  617.0  436.0
2      443   229  227.0   216.0  8.3  534.0  402.0
3      140   525   76.0    64.0  7.6  416.0  366.0
4      249   413  145.0   104.0  9.3  467.0  460.0
..     ...   ...    ...     ...  ...    ...    ...
156      0     0    NaN     NaN  NaN    NaN    NaN
157      0     0    NaN     NaN  NaN    NaN    NaN
158      0     0    NaN     NaN  NaN    NaN    NaN
159      0     0    NaN     NaN  NaN    NaN    NaN
160      0     0    NaN     NaN  NaN    NaN    NaN

[161 rows x 7 columns]

In [64]:
lol=lol.fillna(0)
lol

     Picks  Bans   Wins  Losses  CSM    DPM    GPM
0      373   347  212.0   161.0  5.3  329.0  337.0
1      250   453  130.0   120.0  9.3  617.0  436.0
2      443   229  227.0   216.0  8.3  534.0  402.0
3      140   525   76.0    64.0  7.6  416.0  366.0
4      249   413  145.0   104.0  9.3  467.0  460.0
..     ...   ...    ...     ...  ...    ...    ...
156      0     0    0.0     0.0  0.0    0.0    0.0
157      0     0    0.0     0.0  0.0    0.0    0.0
158      0     0    0.0     0.0  0.0    0.0    0.0
159      0     0    0.0     0.0  0.0    0.0    0.0
160      0     0    0.0     0.0  0.0    0.0    0.0

[161 rows x 7 columns]

In [67]:
Wukong = np.array(lol.iloc[0])
Gnar = np.array(lol.iloc[2])
Aphelios = np.array(lol.iloc[18])

In [79]:
league.iloc[0]['Champion']

'Wukong'

In [68]:
cosine = np.dot(Wukong,Gnar)/(norm(Wukong)*norm(Gnar))
print("Cosine Similarity:", cosine)

Cosine Similarity: 0.9648845815351119

In [100]:
##Code for Wukong
Wukong_indexed_cosine = pd.DataFrame(columns = ['Champion', 'Cosine Similarity'])
for champ in range(lol.shape[0]):
    comp = np.array(lol.iloc[champ])
    cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
    Wukong_indexed_cosine.loc[len(Wukong_indexed_cosine.index)] = [league.iloc[champ]['Champion'],cosine]
    
WukongTop10= Wukong_indexed_cosine.sort_values(by='Cosine Similarity', ascending=False)
WukongTop10.head(10)

<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))
<ipython-input-100-ad8cfdb8c6e0>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Wukong,comp)/(norm(Wukong)*norm(comp))

        Champion  Cosine Similarity
0         Wukong           1.000000
6   Renata Glasc           0.983455
12      Nautilus           0.968041
2           Gnar           0.964885
11         Viego           0.956788
4        Kalista           0.956756
17      Volibear           0.954665
19       Trundle           0.948626
23    Tahm Kench           0.945935
14         Yuumi           0.945626

In [101]:
##Code for Gnar
Gnar_indexed_cosine = pd.DataFrame(columns = ['Champion', 'Cosine Similarity'])
for champ in range(lol.shape[0]):
    comp = np.array(lol.iloc[champ])
    cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
    Gnar_indexed_cosine.loc[len(Gnar_indexed_cosine.index)] = [league.iloc[champ]['Champion'],cosine]
    
GnarTop10= Gnar_indexed_cosine.sort_values(by='Cosine Similarity', ascending=False)
GnarTop10.head(10)

<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))
<ipython-input-101-1a99185be466>:5: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Gnar,comp)/(norm(Gnar)*norm(comp))

      Champion  Cosine Similarity
2         Gnar           1.000000
11       Viego           0.985644
17    Volibear           0.970002
23  Tahm Kench           0.969011
0       Wukong           0.964885
18    Aphelios           0.962099
19     Trundle           0.961012
21        Ornn           0.954349
8        Sylas           0.954045
29       Rakan           0.952517

[['Wukong', ('Cosine Similarity:', 0.9648845815351119)],
 ['Zeri', ('Cosine Similarity:', 0.9323935883530741)],
 ['Gnar', ('Cosine Similarity:', 1.0000000000000002)],
 ['Seraphine', ('Cosine Similarity:', 0.8358938647626359)],
 ['Kalista', ('Cosine Similarity:', 0.9358178468571958)],
 ['Corki', ('Cosine Similarity:', 0.9152292888397311)],
 ['Renata Glasc', ('Cosine Similarity:', 0.9019083528123889)],
 ['Azir', ('Cosine Similarity:', 0.9456786405100943)],
 ['Sylas', ('Cosine Similarity:', 0.9540446768765154)],
 ['Gangplank', ('Cosine Similarity:', 0.9300670489001744)],
 ['Ahri', ('Cosine Similarity:', 0.9509623455417867)],
 ['Viego', ('Cosine Similarity:', 0.985643553943075)],
 ['Nautilus', ('Cosine Similarity:', 0.9463208706474255)],
 ['Senna', ('Cosine Similarity:', 0.9271063182510284)],
 ['Yuumi', ('Cosine Similarity:', 0.9123316056893133)],
 ['Lucian', ('Cosine Similarity:', 0.8897805412972147)],
 ['Gwen', ('Cosine Similarity:', 0.936025839256066)],
 ['Volibear', ('Cosine Similarity:', 0.9700018759020774)],
 ['Aphelios', ('Cosine Similarity:', 0.9620990126486278)],
 ['Trundle', ('Cosine Similarity:', 0.961012499775028)],
 ['Taliyah', ('Cosine Similarity:', 0.9026576311901134)],
 ['Ornn', ('Cosine Similarity:', 0.9543486492173024)],
 ['Poppy', ('Cosine Similarity:', 0.9386322237904893)],
 ['Tahm Kench', ('Cosine Similarity:', 0.9690113094137)],
 ['Lee Sin', ('Cosine Similarity:', 0.9451477341583007)],
 ['Sejuani', ('Cosine Similarity:', 0.9400371583721375)],
 ['Swain', ('Cosine Similarity:', 0.8953086956897716)],
 ['Ezreal', ('Cosine Similarity:', 0.8715603357042829)],
 ['Lissandra', ('Cosine Similarity:', 0.9047845358867954)],
 ['Rakan', ('Cosine Similarity:', 0.952517082133638)],
 ['Jinx', ('Cosine Similarity:', 0.9000131738291025)],
 ['Camille', ('Cosine Similarity:', 0.8885474145443776)],
 ['Belveth', ('Cosine Similarity:', 0.866057575321346)],
 ['Amumu', ('Cosine Similarity:', 0.9516263329641185)],
 ['Lulu', ('Cosine Similarity:', 0.9140882363445804)],
 ['Xin Zhao', ('Cosine Similarity:', 0.9130563728651697)],
 ['Fiora', ('Cosine Similarity:', 0.827531101666836)],
 ['Twitch', ('Cosine Similarity:', 0.8461515408703442)],
 ['Viktor', ('Cosine Similarity:', 0.8434005868817345)],
 ['Akali', ('Cosine Similarity:', 0.8408759451183008)],
 ['Yone', ('Cosine Similarity:', 0.8447739020566097)],
 ['Draven', ('Cosine Similarity:', 0.8232497210311271)],
 ['Karma', ('Cosine Similarity:', 0.875030173652383)],
 ['Braum', ('Cosine Similarity:', 0.9057614224343493)],
 ['Kayle', ('Cosine Similarity:', 0.8182078235462403)],
 ['Gragas', ('Cosine Similarity:', 0.8481051717523618)],
 ['Nami', ('Cosine Similarity:', 0.9045726328432983)],
 ['Aatrox', ('Cosine Similarity:', 0.8234731699341621)],
 ['LeBlanc', ('Cosine Similarity:', 0.7998796298722313)],
 ['Jax', ('Cosine Similarity:', 0.8122875345360165)],
 ['Olaf', ('Cosine Similarity:', 0.8097020128789393)],
 ['Yasuo', ('Cosine Similarity:', 0.811142112147295)],
 ['Diana', ('Cosine Similarity:', 0.8102125272395583)],
 ['Irelia', ('Cosine Similarity:', 0.8020885217939968)],
 ['Lillia', ('Cosine Similarity:', 0.7994751038230326)],
 ['Leona', ('Cosine Similarity:', 0.8263486796468089)],
 ['Xayah', ('Cosine Similarity:', 0.8125537755844152)],
 ['Shyvana', ('Cosine Similarity:', 0.8127495588495494)],
 ['Pyke', ('Cosine Similarity:', 0.8135661445773303)],
 ['Ashe', ('Cosine Similarity:', 0.8194919028503538)],
 ['Udyr', ('Cosine Similarity:', 0.7930722328604514)],
 ['Veigar', ('Cosine Similarity:', 0.7993404502236987)],
 ['Zoe', ('Cosine Similarity:', 0.7914625394647689)],
 ['Kaisa', ('Cosine Similarity:', 0.798207014735938)],
 ['Tristana', ('Cosine Similarity:', 0.7962566950505509)],
 ['Miss Fortune', ('Cosine Similarity:', 0.7880744399354874)],
 ['Vi', ('Cosine Similarity:', 0.7884293435852399)],
 ['Orianna', ('Cosine Similarity:', 0.7904867813093189)],
 ['Sion', ('Cosine Similarity:', 0.8006177909400183)],
 ['Rell', ('Cosine Similarity:', 0.7990881433160736)],
 ['Jarvan IV', ('Cosine Similarity:', 0.7637168375573823)],
 ['Samira', ('Cosine Similarity:', 0.7715307964143034)],
 ['Alistar', ('Cosine Similarity:', 0.7893729135116635)],
 ['Jayce', ('Cosine Similarity:', 0.769084166515937)],
 ['Galio', ('Cosine Similarity:', 0.7826159418183009)],
 ['Darius', ('Cosine Similarity:', 0.7725392971290722)],
 ['Graves', ('Cosine Similarity:', 0.7768757352079023)],
 ['Twisted Fate', ('Cosine Similarity:', 0.7677793309377579)],
 ['Zilean', ('Cosine Similarity:', 0.7871469845368579)],
 ['Nocturne', ('Cosine Similarity:', 0.7687210658386189)],
 ['Ryze', ('Cosine Similarity:', 0.7712615258594149)],
 ['Kindred', ('Cosine Similarity:', 0.7747709708317286)],
 ['Sett', ('Cosine Similarity:', 0.7750126495035674)],
 ['KogMaw', ('Cosine Similarity:', 0.7617082302086277)],
 ['Syndra', ('Cosine Similarity:', 0.7685211428111286)],
 ['Blitzcrank', ('Cosine Similarity:', 0.7642125569301753)],
 ['Karthus', ('Cosine Similarity:', 0.7465126722388471)],
 ['Tryndamere', ('Cosine Similarity:', 0.7663707825660447)],
 ['Zac', ('Cosine Similarity:', 0.7721811281952329)],
 ['Renekton', ('Cosine Similarity:', 0.7718702846722573)],
 ['Cassiopeia', ('Cosine Similarity:', 0.7654889525685462)],
 ['Nidalee', ('Cosine Similarity:', 0.7655834729891504)],
 ['Riven', ('Cosine Similarity:', 0.7608478555948468)],
 ['KhaZix', ('Cosine Similarity:', 0.7647545864246491)],
 ['Mordekaiser', ('Cosine Similarity:', 0.7655377879188003)],
 ['Thresh', ('Cosine Similarity:', 0.743486902912345)],
 ['Rumble', ('Cosine Similarity:', 0.7560799305055027)],
 ['Kayn', ('Cosine Similarity:', 0.7618917693201727)],
 ['Rengar', ('Cosine Similarity:', 0.7602687415541508)],
 ['Soraka', ('Cosine Similarity:', 0.7475886388957825)],
 ['Vladimir', ('Cosine Similarity:', 0.7644900366635665)],
 ['Bard', ('Cosine Similarity:', 0.769681272040866)],
 ['Kennen', ('Cosine Similarity:', 0.7576402650051226)],
 ['Taric', ('Cosine Similarity:', 0.7309617058455246)],
 ['Ziggs', ('Cosine Similarity:', 0.7553349936960868)],
 ['Hecarim', ('Cosine Similarity:', 0.7506433130821661)],
 ['RekSai', ('Cosine Similarity:', 0.748090527478791)],
 ['Akshan', ('Cosine Similarity:', 0.7595430254146796)],
 ['Malphite', ('Cosine Similarity:', 0.7622084679913663)],
 ['Nasus', ('Cosine Similarity:', 0.7592783576307104)],
 ['Jhin', ('Cosine Similarity:', 0.7589626672777763)],
 ['Dr. Mundo', ('Cosine Similarity:', 0.7587123087197429)],
 ['Shen', ('Cosine Similarity:', 0.75440026435248)],
 ['Skarner', ('Cosine Similarity:', 0.6899104549539808)],
 ['Vayne', ('Cosine Similarity:', 0.7571710885695816)],
 ['Qiyana', ('Cosine Similarity:', 0.7591060453039858)],
 ['Kassadin', ('Cosine Similarity:', 0.7553797827750567)],
 ['Sona', ('Cosine Similarity:', 0.7432194823755797)],
 ['Zed', ('Cosine Similarity:', 0.7545037116837567)],
 ['VelKoz', ('Cosine Similarity:', 0.7311763918208845)],
 ['Chogath', ('Cosine Similarity:', 0.7525268272857212)],
 ['Xerath', ('Cosine Similarity:', 0.7400161568948229)],
 ['Ivern', ('Cosine Similarity:', 0.7028077671551617)],
 ['Anivia', ('Cosine Similarity:', 0.752921298963376)],
 ['Annie', ('Cosine Similarity:', 0.25704326433805175)],
 ['Shaco', ('Cosine Similarity:', 0.7544267812521842)],
 ['Aurelion Sol', ('Cosine Similarity:', 0.7532222160932641)],
 ['Kled', ('Cosine Similarity:', 0.7550208442542236)],
 ['Caitlyn', ('Cosine Similarity:', 0.7554380142233169)],
 ['Heimerdinger', ('Cosine Similarity:', 0.7504844002427485)],
 ['Morgana', ('Cosine Similarity:', 0.754969479336026)],
 ['Urgot', ('Cosine Similarity:', 0.7504847834944258)],
 ['Brand', ('Cosine Similarity:', 0.7339837693691408)],
 ['Varus', ('Cosine Similarity:', 0.750308890541613)],
 ['Janna', ('Cosine Similarity:', 0.716374899544217)],
 ['Elise', ('Cosine Similarity:', 0.7493010521624631)],
 ['Fiddlesticks', ('Cosine Similarity:', 0.7443598652975318)],
 ['Lux', ('Cosine Similarity:', 0.7520788000299548)],
 ['Maokai', ('Cosine Similarity:', 0.25704326433805175)],
 ['Singed', ('Cosine Similarity:', 0.7130134344302366)],
 ['Sivir', ('Cosine Similarity:', 0.7515893451586679)],
 ['Talon', ('Cosine Similarity:', 0.7512793254197563)],
 ['Ekko', ('Cosine Similarity:', 0.7462249196217724)],
 ['Neeko', ('Cosine Similarity:', 0.7511536705174267)],
 ['Vex', ('Cosine Similarity:', 0.7495133256084371)],
 ['Garen', ('Cosine Similarity:', 0.750177264481813)],
 ['Katarina', ('Cosine Similarity:', 0.25704326433805175)],
 ['Nunu', ('Cosine Similarity:', 0.7481249506862843)],
 ['Pantheon', ('Cosine Similarity:', 0.7507625863583792)],
 ['Rammus', ('Cosine Similarity:', 0.25704326433805175)],
 ['Teemo', ('Cosine Similarity:', 0.7480980170520727)],
 ['Yorick', ('Cosine Similarity:', 0.25704326433805175)],
 ['Evelynn', ('Cosine Similarity:', nan)],
 ['Fizz', ('Cosine Similarity:', nan)],
 ['Malzahar', ('Cosine Similarity:', nan)],
 ['Master Yi', ('Cosine Similarity:', nan)],
 ['Quinn', ('Cosine Similarity:', nan)],
 ['Warwick', ('Cosine Similarity:', nan)],
 ['Zyra', ('Cosine Similarity:', nan)],
 ['Illaoi', ('Cosine Similarity:', nan)],
 ['Nilah', ('Cosine Similarity:', nan)]]

In [ ]:
##Code for Aphelios

In [102]:
Aphelios_indexed_cosine = pd.DataFrame(columns = ['Champion', 'Cosine Similarity'])
for champ in range(lol.shape[0]):
    comp = np.array(lol.iloc[champ])
    cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
    Aphelios_indexed_cosine.loc[len(Aphelios_indexed_cosine.index)] = [league.iloc[champ]['Champion'],cosine]
  

ApheliosTop10= Aphelios_indexed_cosine.sort_values(by='Cosine Similarity', ascending=False)
ApheliosTop10.head(10)

<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))
<ipython-input-102-38e9421971bb>:4: RuntimeWarning: invalid value encountered in double_scalars
  cosine = np.dot(Aphelios,comp)/(norm(Aphelios)*norm(comp))

     Champion  Cosine Similarity
18   Aphelios           1.000000
25    Sejuani           0.989250
21       Ornn           0.981366
30       Jinx           0.981205
35   Xin Zhao           0.980800
28  Lissandra           0.972323
24    Lee Sin           0.969590
33      Amumu           0.969316
46       Nami           0.968583
16       Gwen           0.967627

In [95]:
Aphelios_indexed_cosine.sort_values(by='Cosine Similarity', ascending=False)

     Champion  Cosine Similarity
18   Aphelios           1.000000
25    Sejuani           0.989250
21       Ornn           0.981366
30       Jinx           0.981205
35   Xin Zhao           0.980800
..        ...                ...
156     Quinn                NaN
157   Warwick                NaN
158      Zyra                NaN
159    Illaoi                NaN
160     Nilah                NaN

[161 rows x 2 columns]